# Site settings
title: Code-ventures with Meredith
header-img: img/home-bg.png
email: nerdybug@gmail.com
copyright_name: nerdybug
description: > # this means to ignore newlines until "baseurl:"
  "It is never too late to be what you might have been" -- George Eliot
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: nerdybug
github_username:  nerdybug
learn_profile: nerdybug
email_username: nerdybug@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
